name: ci

on: [push, pull_request]

jobs:
  ci:
    # Set up operating system
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    
    - name: Checkout repository
      uses: actions/checkout@v2
  
    - name: Install Poetry
      uses: snok/install-poetry@v1
    
    - name: Install package
      run: poetry install
   
    - name: Test with pytest
      run: poetry run pytest tests/ --cov=PACKAGE_NAME --cov-report=xml
      
    - name: Upload coverage to Codecov  
      uses: codecov/codecov-action@v2
      with:
        file: ./coverage.xml    # coverage report
        fail_ci_if_error: true
